In [1]:
# Face Recognition

# Importing the libraries
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('facefeatures_new_model.h5')

In [2]:
# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face


In [3]:
# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][2]>0.5):
            name='Krish'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[2.4182299e-11 7.2000649e-16 1.0000000e+00]]
[[1.0623500e-04 9.9989283e-01 1.0029019e-06]]
[[1.7739259e-25 4.3840867e-08 1.0000000e+00]]
[[1.0000000e+00 1.5452607e-29 2.2860815e-23]]
[[2.239395e-15 4.527678e-28 1.000000e+00]]
[[1.1891989e-13 3.9785100e-18 1.0000000e+00]]
[[5.8256606e-29 2.6635871e-18 1.0000000e+00]]
[[4.4847147e-06 3.8964527e-07 9.9999511e-01]]
[[8.727604e-18 7.890949e-10 1.000000e+00]]
[[2.0850850e-08 2.5292635e-09 1.0000000e+00]]
[[8.1557057e-28 5.5210766e-14 1.0000000e+00]]
[[7.8322887e-14 1.4610156e-14 1.0000000e+00]]
[[2.1785072e-13 1.3993493e-09 1.0000000e+00]]
[[2.1313443e-14 3.6149442e-02 9.6385050e-01]]
[[2.7267398e-12 6.1297339e-17 1.0000000e+00]]
[[3.5257518e-30 2.0200972e-12 1.0000000e+00]]
[[1.2367828e-29 2.4379873e-18 1.0000000e+00]]
[[9.9999952e-01 2.2256682e-20 4.3206151e-07]]
[[8.6173955e-13 0.0000000e+00 1.0000000e+00]]
[[1.7871053e-37 0.0000000e+00 1.0000000e+00]]
[[5.757160e-19 2.778959e-36 1.000000e+00]]
[[3.4255584e-18 9.9129865e-16 1.0000000e+00